package model

import (
	"context"
	"fmt"
	"strings"
)

// ContentBlockType discriminates the kind of content in a ContentBlock.
type ContentBlockType string

const (
	ContentBlockText     ContentBlockType = "text"
	ContentBlockImage    ContentBlockType = "image"
	ContentBlockDocument ContentBlockType = "document"
)

// ContentBlock represents a single piece of content within a message.
// For text blocks only Text is populated. For image/document blocks,
// MediaType and either Data (base64) or URL are set.
type ContentBlock struct {
	Type      ContentBlockType `json:"type"`
	Text      string           `json:"text,omitempty"`
	MediaType string           `json:"media_type,omitempty"` // e.g. "image/jpeg", "application/pdf"
	Data      string           `json:"data,omitempty"`       // base64-encoded content
	URL       string           `json:"url,omitempty"`        // URL source (alternative to Data)
}

// Message represents a single conversational turn.
// Tool calls emitted by the assistant are kept on ToolCalls.
// When ContentBlocks is non-empty it takes precedence over Content for
// multimodal messages (images, documents). Existing text-only callers
// continue to use Content unchanged.
type Message struct {
	Role             string
	Content          string
	ContentBlocks    []ContentBlock // Multimodal content; takes precedence over Content when non-empty
	ToolCalls        []ToolCall
	ReasoningContent string // For thinking models (e.g. DeepSeek, Kimi k2.5)
}

// PlaceholderAssistantContent is sent to some providers when an assistant turn
// has no user-visible text (e.g. tool-only turns). It must not be shown to users.
const PlaceholderAssistantContent = "."

// IsPlaceholderAssistantContent reports whether content is the API placeholder
// used for empty assistant text.
func IsPlaceholderAssistantContent(content string) bool {
	return strings.TrimSpace(content) == PlaceholderAssistantContent
}

// NormalizeAssistantContent strips placeholder-only text from tool-call turns.
func NormalizeAssistantContent(content string, hasToolCalls bool) string {
	if hasToolCalls && IsPlaceholderAssistantContent(content) {
		return ""
	}
	return content
}

// TextContent returns the text portion of the message. When ContentBlocks
// is populated it concatenates all text blocks; otherwise it falls back to
// Content.
func (m Message) TextContent() string {
	if len(m.ContentBlocks) == 0 {
		return m.Content
	}
	var parts []string
	for _, b := range m.ContentBlocks {
		if b.Type == ContentBlockText && b.Text != "" {
			parts = append(parts, b.Text)
		}
	}
	if len(parts) == 0 {
		return m.Content
	}
	return strings.Join(parts, "")
}

// ToolCall captures a function-style invocation generated by the model.
type ToolCall struct {
	ID        string
	Name      string
	Arguments map[string]any
	Result    string // Result stores the execution result for this specific tool call
}

// ToolDefinition describes a callable function exposed to the model.
type ToolDefinition struct {
	Name        string
	Description string
	Parameters  map[string]any
}

// HasSubstantialToolParameters reports whether params include property metadata beyond
// a bare JSON Schema object shell (type: object with no properties).
func HasSubstantialToolParameters(params map[string]any) bool {
	if len(params) == 0 {
		return false
	}
	props, ok := params["properties"]
	if !ok {
		if len(params) == 1 {
			if t, ok := params["type"]; ok {
				return strings.TrimSpace(fmt.Sprint(t)) != "object"
			}
		}
		return len(params) > 0
	}
	if m, ok := props.(map[string]any); ok {
		return len(m) > 0
	}
	return true
}

// Request drives a single model completion.
type Request struct {
	Messages          []Message
	Tools             []ToolDefinition
	System            string
	Model             string
	SessionID         string
	MaxTokens         int
	Temperature       *float64
	EnablePromptCache bool // Enable prompt caching for system and recent messages
}

// Usage reports token accounting for a completion.
type Usage struct {
	InputTokens         int
	OutputTokens        int
	TotalTokens         int
	CacheReadTokens     int
	CacheCreationTokens int
}

// Response wraps the final assistant message and accounting.
type Response struct {
	Message    Message
	Usage      Usage
	StopReason string
}

// StreamResult delivers incremental updates during streaming calls.
type StreamResult struct {
	Delta    string
	ToolCall *ToolCall
	Final    bool
	Response *Response
}

// StreamHandler consumes streaming updates in order.
type StreamHandler func(StreamResult) error

// Model is the provider-agnostic interface used by the agent runtime.
type Model interface {
	Complete(ctx context.Context, req Request) (*Response, error)
	CompleteStream(ctx context.Context, req Request, cb StreamHandler) error
}
